### ISSUE TITLE
Frontend hello world

### ISSUE THREAD

**Issue by conatus** [commonknowledge/vent-your-rent#1]
# Todo

- [x] Add Create React App basics to repository
- [x] Block out components from Figma into flats with sensible splits, minus styling
- [x] Add outline button component

**Comment by conatus** [comment]
See https://github.com/commonknowledge/vent-your-rent/pull/2
