### ISSUE TITLE
Venter can see statistics by searching by postcode

### ISSUE THREAD

**Issue by conatus** [commonknowledge/vent-your-rent#10]
# User story
- As a venter
- So I can learn about the rent crisis in your area
- I can see constituency statistics about my area by searching on postcode

# Acceptance criteria
- Can I search by postcode to find statistics on renting in my area?
- Are the statistics displayed alongside a relevant demand?

**Comment by conatus** [comment]
# Todo
- [ ] Fix up page header
- [ ] Update copy
- [ ] Complete Demand block - with temporary read full manifesto link for now
- [ ] Add bar graphs to Statistics component
- [ ] Use hooks to pass state - try not to use Redux or similar
- [ ] Hooks to do user interaction with form
- [ ] Call GraphQL to retrieve statistics
- [ ] Restyle first page to accord with designs

**Comment by conatus** [comment]
@janbaykara if you. want to dump in on any of these then let me know. Currently fixing Demand block.

**Comment by conatus** [comment]
See https://github.com/commonknowledge/vent-your-rent/pull/6 for ongoing progress

**Comment by janbaykara** [comment]
Accidental LGTM merge on #6! In any case, all major branches merged in now. Check #11 to wire up front and backend via GraphQL.

Only thing I can think we'll need out of the API is baselined national data and potentially some other statistics to satisfy the designs. This should be easy to bolt on.

**Comment by conatus** [comment]
@janbaykara 

Do you have an example of the GraphQL required in each case? Realise I can explore the API but might be quicker to have an example.

**Comment by conatus** [comment]
Have the GraphQL in hand via https://github.com/commonknowledge/vent-your-rent/pull/11 - proceeding to clean this up.

**Comment by conatus** [comment]
@janbaykara if you could handle "Add private renters in constituency from CSV" on the PR that would be amazing.
