### ISSUE TITLE
Venter can sign manifesto by their name

### ISSUE THREAD

**Issue by conatus** [commonknowledge/vent-your-rent#12]
# User Story
- As a venter
- So I can feel like I am part of a movement in favour of renters
- I can sign the manifesto with my name

**Comment by conatus** [comment]
Requires https://github.com/commonknowledge/vent-your-rent/pull/11 to be merged, which contains the backend mutation for image uploads.

**Comment by conatus** [comment]
# Todo
- [ ] Make GraphQL mutation actually hit endpoint and check save
- [ ] Validate input lightly on frontend
- [ ] Read out vents in component via GraphQL

**Comment by conatus** [comment]
We require a few more fields here to fulfil the designs https://github.com/commonknowledge/vent-your-rent/blob/master/vent_your_rent/api/models.py#L14-L23

```
last_name
email
keep_me_updated
```

**Comment by conatus** [comment]
@janbaykara and I have put the basic reading and writing code together now on - https://github.com/commonknowledge/vent-your-rent/pull/13
